apiVersion: mps.playfab.com/v1alpha1
kind: GameServerBuild
metadata:
  name: gameserverbuild-sample # required, name of the GameServerBuild
spec:
  titleID: "$title_id" # required, corresponds to a unique ID for your game. Can be an arbitrary string
  buildID: "$build_id" # required, build ID of your game, must be GUID. Will be used for allocations, must be unique for each Build/version of your game server
  standingBy: 2 # required, number of standing by servers to create
  max: 4 # required, max number of servers to create. Sum of active+standingBy+initializing servers will never be larger than max
  crashesToMarkUnhealthy: 5 # optional. It is the number of crashes needed to mark the GameServerBuild unhealthy. Once this happens, no other operation will take place. If it is not set, Thundernetes will keep creating new GameServers as the old ones crash
  buildMetadata: # optional. Retrievable via GSDK, used to customize your game server
    - key: "rules"
      value: "1"
  portsToExpose: 
    - 80
  template:
    spec:
      # https://playfab.github.io/thundernetes/howtos/scheduling.html
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: BuildID
                  operator: In
                  values:
                  - "$build_id"
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: $acr/$image:$tag # image of your game server
          name: gameserver-sample # name of the container. 
          ports:
          - containerPort: 80 # port that you want to expose
            name: gameport # name of the port that you want to expose. 